<a href="https://colab.research.google.com/github/divyanshibargal/ML-Lab/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Creating a numpy array from python list.

In [ ]:
l = [1,2,3,4,5,6,7,8]
arr = np.array(l)
print("List: ", l)
print("Array: ",arr)
print()
print(type(arr))

List:  [1, 2, 3, 4, 5, 6, 7, 8]
Array:  [1 2 3 4 5 6 7 8]

<class 'numpy.ndarray'>


Having just few string elements in the python list, the numpy ndarray converts the whole list in the form of a string and didn't gave any error

In [ ]:
ls = [1,4,"String", 1.304903,"float"]
arr = np.array(ls)
print("List: ", ls)
print("Array: ", arr)

List:  [1, 4, 'String', 1.304903, 'float']
Array:  ['1' '4' 'String' '1.304903' 'float']


In [ ]:
# performing addition in numpy arrays: either both should be of equal size otherwise
# there should be just one element in one of the array in order to perform broadcasting.

a = np.array([1,2,4,5,6])
b = np.array([23,39,29,59,2])
c = np.array([10])

print("Sum of a and b is: ", a+b)
print("Sum of a and c is: ", a+c)

Sum of a and b is:  [24 41 33 64  8]
Sum of a and c is:  [11 12 14 15 16]


In [ ]:
# performing dot product of two arrays

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([9,1,59,39,4])

print("Dot Product of arr1 and arr2 is: ", np.dot(arr1,arr2))

Dot Product of arr1 and arr2 is:  364


In [ ]:
# Performance Determination of arrays and python by memory usage
import sys
l = [1,2,3,4,5,6]
a = np.array(l)

print("Memory Usage for list is: ", sys.getsizeof(l))
print("Memory Usage for array is: ", a.nbytes)

Memory Usage for list is:  104
Memory Usage for array is:  48


In [ ]:
# creating np array from python lists and tuples

list1 = [1,2,3,4,5,6]
tuple1 = (1,2,3,4,5,6)

arr1 = np.array(list1)
arr2 = np.array(tuple1)

print("Array from list: ", arr1)
print("Array from tuple: ", arr2)

Array from list:  [1 2 3 4 5 6] 48
Array from tuple:  [1 2 3 4 5 6] 48


In [ ]:
# creating a higher dimesional array from list which can be done by just nesting the lists

nested_list = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]

array = np.array(nested_list)
print("2-D array is: ")
print(array)

2-D array is: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# creating higher dimensional arrays using array creation functions

# 1-d array

array = np.arange(2,20,0.5,dtype=float)
print(array)

[ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5
 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [ ]:
# np.linspace enables you get evenly spaced data points between a range.

array = np.linspace(2,3,num=5)
print(array)

[2.   2.25 2.5  2.75 3.  ]


In [ ]:
# 2-D array
np.eye(4,4) # diagonal matrix with diagonal elements one and rest 0

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# 3-d arrays
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((5,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.empty([3,3], dtype=int) # gives uninitialised list with random data

array([[219043332146,            0,            0],
       [           0,            0,            0],
       [           0,            0,            0]])